import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Real metadata (confirmed 2026-08-06, landing page build) — this was
// still the literal create-next-app default ("Create Next App" /
// "Generated by create next app") until now, confirmed live in every
// browser tab throughout this build. Fixed here as an unavoidable
// prerequisite of shipping a real landing page, not a separate design-
// audit fix — the rest of that audit (font-family bug, favicon, brand
// color, logo) stays reported-not-fixed pending explicit go-ahead.
export const metadata: Metadata = {
  title: "Elvanis — Know your top 3 execution priorities",
  description:
    "A goal-driven execution audit for founder-led B2B teams. Submit your evidence, get back your top 3 bottlenecks with financial impact and a 90-day roadmap — reviewed by a human before you ever see it.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
